FROM arm32v7/ubuntu:latest

MAINTAINER cade <cade.call@mediciventures.com>

EXPOSE $RPCPORT

EXPOSE $PORT

RUN useradd -ms /bin/bash akitacoin

RUN mkdir /etc/akitacoin

RUN mkdir /var/lib/akitacoin

RUN chown akitacoin:akitacoin /etc/akitacoin /var/lib/akitacoin

WORKDIR /home/akitacoin

COPY --chown=akitacoin:akitacoin linux64/* ./run.sh /home/akitacoin/

USER akitacoin

CMD ["/home/akitacoin/run.sh"]
